logging:
  level:
    org.springframework.security: INFO
  path: /var/logs/
  file:
    max-size: 1GB

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://auth-service:5000/uaa/users/current

spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    # 表示是否将自己注册到Eureka Server中，默认为true, 由于当前应用就是 Eureka Server， 故而设置为false
#    #    registerWithEureka: false
#    # 表示是否从 Eureka Server中获取注册信息, 默认为true, 因为这是一个单点的 Eureka Server, 不需要同步其它的 Eureka Server 节点的数据， 故而设置为 false
#    #    fetchRegistry: false
#    service-url:
#      # 设置与Eureka Server交互的地址， 查询服务和注册服务都需要依赖这个地址. 默认http://localhost:8761/eureka; 多个地址可以使用","分隔
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
##    enable-self-preservation: false   # 设为false，关闭自我保护
##    eviction-interval-timer-in-ms: 15000  # 清理间隔（单位毫秒，默认是60*1000）